/***automatically generated by terradota***/
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace TerraDota.Items
{
    public class TownPortalScroll : ModItem
    {
    }
}