/***automatically generated by terradota***/
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace TerraDota.Items
{
    public class TownPortalScroll : ModItem
    {
        public override void SetStaticDefaults()
        {
            Tooltip.SetDefault("teleports you to home.");
        }

        public override void SetDefaults()
        {
            Item.SetNameOverride("Town Portal Scroll");
            Item.damage = 0;
        }

        public override void AddRecipes()
        {
        }

        public override bool? UseItem()
        {
            return true;
        }
    }
}