/***automatically generated by terradota***/
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace TerraDota.Items
{
    public class TownPortalScroll : ModItem
    {
        public override void SetStaticDefaults()
        {
        }

        public override void SetDefaults()
        {
        }

        public override void AddRecipes()
        {
        }
    }
}